import Link from "next/link";

export function Header() {
  return (
    <header>
      <nav>
        <ul className="flex list-none flex-row items-center justify-center gap-5 py-5 font-medium tracking-tight">
          <li>
            <Link
              href="/"
              className={`relative
              cursor-pointer
              px-4
              py-2
              text-center
              text-lg
              before:absolute 
              before:bottom-0
              before:left-0
              before:h-px
              before:w-full
              before:origin-bottom-left
              before:scale-x-0
              before:bg-white
              before:transition
              before:duration-300
              hover:before:scale-x-100`}
            >
              Home
            </Link>
          </li>
          <li>
            <Link
              href="/skills"
              className={`
              relative
              cursor-pointer
              px-4
              py-2
              text-center
              text-lg
              before:absolute
              before:bottom-0
              before:left-0
              before:h-px
              before:w-full
              before:origin-bottom-left
              before:scale-x-0
              before:bg-white
              before:transition
              before:duration-300
              hover:before:scale-x-100`}
            >
              Habilidades
            </Link>
          </li>
          <li>
            <Link
              href="#"
              className={`
               relative
               cursor-pointer
               px-4
               py-2
               text-center
               text-lg
               before:absolute 
               before:bottom-0
               before:left-0
               before:h-px
               before:w-full
               before:origin-bottom-left
               before:scale-x-0
               before:bg-white
               before:transition
               before:duration-300
               hover:before:scale-x-100`}
            >
              Sobre mim
            </Link>
          </li>
          <li>
            <Link
              href="#"
              className={`relative
              cursor-pointer
              px-4
              py-2
              text-center
              text-lg
              before:absolute 
              before:bottom-0
              before:left-0
              before:h-px
              before:w-full
              before:origin-bottom-left
              before:scale-x-0
              before:bg-white
              before:transition
              before:duration-300
              hover:before:scale-x-100`}
            >
              Carreira
            </Link>
          </li>
          <li>
            <Link
              href="#"
              className={`relative 
                cursor-pointer px-4 
                py-2 text-center 
                text-lg before:absolute 
                before:bottom-0 
                before:left-0 
                before:h-px before:w-full 
                before:origin-bottom-left 
                before:scale-x-0 
                before:bg-white 
                before:transition 
                before:duration-300 
                hover:before:scale-x-100`}
            ></Link>
          </li>
        </ul>
      </nav>
    </header>
  );
}
